env:
  browser: true
  es2021: true
extends:
  - 'plugin:@next/next/recommended'
  - 'plugin:react/recommended'
  - airbnb
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  {
    'react/prop-types': 'off',
    'react/jsx-props-no-spreading': 'off',
    'react/no-unknown-property': ['error', { ignore: ['css'] }],
    'jsx-a11y/label-has-associated-control': 'off',
    'import/extensions':
      ['error', 'ignorePackages', { 'js': 'never', 'jsx': 'never' }],
    'import/no-unresolved': 'off',
    'react/button-has-type': 'off',
    'import/prefer-default-export': 'off',
  }
plugins:
  - react
  - prettier
